package beziercurves;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;
import java.io.File;
import javax.swing.JFileChooser;

public class Application extends javax.swing.JFrame {
    
    BezierCurves curve;
    
    class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Allow only directories, or files with ".txt" extension
            return file.isDirectory() || file.getAbsolutePath().endsWith(".jpg");
        }
        @Override
        public String getDescription() {
            // This description will be displayed in the dialog,
            // hard-coded = ugly, should be done via I18N
            return "Text documents (*.jpg)";
        }
    } 

    /**
     * Creates new form Application
     */
    public Application() {
        curve = new BezierCurves();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        colorChooserDialog = new javax.swing.JDialog();
        colorChooserButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        colorChooser = new javax.swing.JColorChooser();
        aboutDialog = new javax.swing.JDialog();
        closeAboutDialog = new javax.swing.JButton();
        aboutText = new javax.swing.JLabel();
        instructionDialog = new javax.swing.JDialog();
        closeInstrDialog = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        methods = new javax.swing.ButtonGroup();
        lowerPrompt = new javax.swing.JDialog();
        deelevate = new javax.swing.JRadioButton();
        approx = new javax.swing.JRadioButton();
        hermite = new javax.swing.JRadioButton();
        PWo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        colorButton = new javax.swing.JButton();
        lowerDegree = new javax.swing.JButton();
        higherDegree = new javax.swing.JButton();
        convexHull = new javax.swing.JCheckBox();
        clear = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        Quit = new javax.swing.JMenuItem();
        Help = new javax.swing.JMenu();
        Instruction = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("Choose a file");
        fileChooser.setFileFilter(new MyCustomFilter());

        colorChooserDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        colorChooserDialog.setTitle("Color Chooser");
        colorChooserDialog.setBounds(new java.awt.Rectangle(375, 225, 50, 50));
        colorChooserDialog.setMinimumSize(new java.awt.Dimension(491, 300));

        colorChooserButton.setText("Zapisz");
        colorChooserButton.setToolTipText("Wybierz ten kolor");
        colorChooserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorChooserButtonActionPerformed(evt);
            }
        });

        colorChooser.setBackground(new java.awt.Color(187, 164, 186));
        colorChooser.setMinimumSize(new java.awt.Dimension(450, 250));
        colorChooser.setPreferredSize(new java.awt.Dimension(450, 250));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout colorChooserDialogLayout = new javax.swing.GroupLayout(colorChooserDialog.getContentPane());
        colorChooserDialog.getContentPane().setLayout(colorChooserDialogLayout);
        colorChooserDialogLayout.setHorizontalGroup(
            colorChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorChooserDialogLayout.createSequentialGroup()
                .addContainerGap(435, Short.MAX_VALUE)
                .addComponent(colorChooserButton)
                .addGap(15, 15, 15))
            .addGroup(colorChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        colorChooserDialogLayout.setVerticalGroup(
            colorChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, colorChooserDialogLayout.createSequentialGroup()
                .addContainerGap(238, Short.MAX_VALUE)
                .addComponent(colorChooserButton)
                .addGap(35, 35, 35))
            .addGroup(colorChooserDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        aboutDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        aboutDialog.setTitle("O autorze");
        aboutDialog.setAlwaysOnTop(true);
        aboutDialog.setBounds(new java.awt.Rectangle(500, 250, 261, 193));
        aboutDialog.setMinimumSize(new java.awt.Dimension(261, 193));

        closeAboutDialog.setText("Zamknij");
        closeAboutDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAboutDialogActionPerformed(evt);
            }
        });

        aboutText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutText.setText("<html>  Autor: Olga Rosik-Rosińska <br>\nnr indeksu 248058 <br>\nInstytut Informatyki <br>\nUniwersytet Wrocławski <br> \nrok akademicki 2012/13 <br>\n</html>");
        aboutText.setToolTipText("");

        javax.swing.GroupLayout aboutDialogLayout = new javax.swing.GroupLayout(aboutDialog.getContentPane());
        aboutDialog.getContentPane().setLayout(aboutDialogLayout);
        aboutDialogLayout.setHorizontalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutText, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(aboutDialogLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(closeAboutDialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        aboutDialogLayout.setVerticalGroup(
            aboutDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeAboutDialog)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        instructionDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        instructionDialog.setTitle("Instrukcje");
        instructionDialog.setAlwaysOnTop(true);
        instructionDialog.setBounds(new java.awt.Rectangle(500, 250, 297, 300));
        instructionDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        closeInstrDialog.setText("Zamknij");
        closeInstrDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeInstrDialogActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html>\n<h2> Edytor krzywych Beziera </h2>\n\n<p> Rozpocznij przygodę z krzywymi Beziera! <br>\nKlikając na edytor, stworzysz punkty kontrolne. <br>\nMenu z boku pomoże ci edytować krzywą: <br>\nzwiększać oraz zmniejszać jej stopień, <br>\nzmieniać kolor na twój ulubiony. <br>\nPrzeciągając punkty zmieniasz kształt krzywej. </p>\n<br><br>\n<p>\nPrzyłącz się już dziś!\n</p> </html>");

        javax.swing.GroupLayout instructionDialogLayout = new javax.swing.GroupLayout(instructionDialog.getContentPane());
        instructionDialog.getContentPane().setLayout(instructionDialogLayout);
        instructionDialogLayout.setHorizontalGroup(
            instructionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(instructionDialogLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(closeInstrDialog)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instructionDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        instructionDialogLayout.setVerticalGroup(
            instructionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, instructionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(closeInstrDialog)
                .addContainerGap())
        );

        lowerPrompt.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        lowerPrompt.setAlwaysOnTop(true);
        lowerPrompt.setBounds(new java.awt.Rectangle(450, 275, 350, 200));
        lowerPrompt.setResizable(false);

        methods.add(deelevate);
        deelevate.setSelected(true);
        deelevate.setText("odwrotność podwyższenia stopnia");
        deelevate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deelevateActionPerformed(evt);
            }
        });

        methods.add(approx);
        approx.setText("wykorzystanie aproksymacji jednostajnej");
        approx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approxActionPerformed(evt);
            }
        });

        methods.add(hermite);
        hermite.setText("wykorzystanie interpolacji Hermite'a");
        hermite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hermiteActionPerformed(evt);
            }
        });

        methods.add(PWo);
        PWo.setText("wykorzystanie aproksymacji średniokwadratowej");
        PWo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Wybierz ulubioną metodę");

        javax.swing.GroupLayout lowerPromptLayout = new javax.swing.GroupLayout(lowerPrompt.getContentPane());
        lowerPrompt.getContentPane().setLayout(lowerPromptLayout);
        lowerPromptLayout.setHorizontalGroup(
            lowerPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPromptLayout.createSequentialGroup()
                .addGroup(lowerPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lowerPromptLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(lowerPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(approx)
                            .addComponent(deelevate)))
                    .addGroup(lowerPromptLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(lowerPromptLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(PWo))
                    .addGroup(lowerPromptLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(hermite)))
                .addContainerGap())
        );
        lowerPromptLayout.setVerticalGroup(
            lowerPromptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerPromptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deelevate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(approx)
                .addGap(12, 12, 12)
                .addComponent(hermite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PWo)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 200, 420, 300));

        jPanel1.setBackground(new java.awt.Color(247, 241, 246));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jToolBar1.setBackground(new java.awt.Color(183, 81, 211));
        jToolBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(70, 36, 104), 1, true));
        jToolBar1.setForeground(new java.awt.Color(131, 86, 140));
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        colorButton.setBackground(new java.awt.Color(170, 154, 180));
        colorButton.setText("Kolor");
        colorButton.setToolTipText("wybierz kolor krzywej");
        colorButton.setAlignmentX(0.5F);
        colorButton.setFocusable(false);
        colorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        colorButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        colorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorButtonActionPerformed(evt);
            }
        });

        lowerDegree.setBackground(new java.awt.Color(170, 154, 180));
        lowerDegree.setText("stopień -");
        lowerDegree.setToolTipText("zmniejsz stopień krzywej o 1");
        lowerDegree.setAlignmentX(0.5F);
        lowerDegree.setFocusable(false);
        lowerDegree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lowerDegree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lowerDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowerDegreeActionPerformed(evt);
            }
        });

        higherDegree.setBackground(new java.awt.Color(170, 154, 180));
        higherDegree.setText("stopień +");
        higherDegree.setToolTipText("zwiększ stopień o 1");
        higherDegree.setFocusable(false);
        higherDegree.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        higherDegree.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        higherDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                higherDegreeActionPerformed(evt);
            }
        });

        convexHull.setBackground(new java.awt.Color(185, 173, 199));
        convexHull.setText("otoczka");
        convexHull.setToolTipText("Pokaż otoczkę wypukłą");
        convexHull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convexHullActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(170, 154, 180));
        clear.setText("Wyczyść");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(higherDegree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lowerDegree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(colorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(2, 12, Short.MAX_VALUE)
                .addComponent(convexHull)
                .addContainerGap())
            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(colorButton)
                .addGap(12, 12, 12)
                .addComponent(lowerDegree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(higherDegree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(convexHull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear)
                .addGap(0, 76, Short.MAX_VALUE))
        );

        jToolBar1.add(jPanel2);

        menuBar.setBackground(new java.awt.Color(144, 85, 206));

        Menu.setBackground(new java.awt.Color(185, 178, 189));
        Menu.setText("Menu");

        Open.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        Open.setText("Otwórz obraz");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        Menu.add(Open);

        Save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Save.setText("Zapisz");
        Menu.add(Save);

        Quit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        Quit.setText("Zamknij");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        Menu.add(Quit);

        menuBar.add(Menu);

        Help.setBackground(new java.awt.Color(185, 178, 189));
        Help.setText("Pomoc");

        Instruction.setText("Instrukcja obsługi");
        Instruction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstructionActionPerformed(evt);
            }
        });
        Help.add(Instruction);

        About.setText("O autorze");
        About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        Help.add(About);

        menuBar.add(Help);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void colorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorButtonActionPerformed
        colorChooserDialog.setVisible(true);
    }//GEN-LAST:event_colorButtonActionPerformed

    private void higherDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_higherDegreeActionPerformed
        if(curve.degree > 0) {
            curve.elevateDegree(jPanel1.getGraphics());
        }
    }//GEN-LAST:event_higherDegreeActionPerformed

    private void clearPoints(){
        Graphics g = jPanel1.getGraphics();
        g.setColor(jPanel1.getBackground());
        
        if(convexHull.isSelected()){
            Tools.evalConvexHull(curve, g, false);
        }
        curve.drawCurve(g);
        for (int i=0; i <curve.degree; i++){
            g.drawOval(curve.points[i].x, curve.points[i].y, 3, 3);
            curve.points[i] = null;
        }
        curve.degree = 0;
    }
	
	private void drawPoints() {
		Graphics g = jPanel1.getGraphics();
		g.setColor(curve.colour);
		
		for(int i=0; i<curve.degree; i++){
			g.drawOval(curve.points[i].x, curve.points[i].y, 3, 3);
		}
	}
	
    private void lowerDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowerDegreeActionPerformed
		lowerPrompt.setVisible(true);
    }//GEN-LAST:event_lowerDegreeActionPerformed

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
        }
    }//GEN-LAST:event_OpenActionPerformed

    private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
        aboutDialog.setVisible(true);
    }//GEN-LAST:event_AboutActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed

    private void colorChooserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorChooserButtonActionPerformed
        Color col = colorChooser.getColor();
        curve.colour = col;
        colorChooserDialog.dispose();
        Graphics g = jPanel1.getGraphics();
        g.setColor(col);
        drawPoints();
        curve.drawCurve(g);
        convexHullActionPerformed(evt);
    }//GEN-LAST:event_colorChooserButtonActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        Graphics g = jPanel1.getGraphics();
        g.setColor(jPanel1.getBackground());
        curve.drawCurve(g);
        g.setColor(curve.colour);
        Point a = jPanel1.getMousePosition();
        g.drawOval(a.x, a.y, 3, 3);
        if(convexHull.isSelected() && curve.degree > 1){
			Tools.evalConvexHull(curve, g, false);
		}
		drawPoints();
		g.setColor(curve.colour);
        int n = curve.degree;
        curve.points[n] = a;
        curve.weight[n] = 1;
        curve.degree ++;
        curve.drawCurve(g);
        if(convexHull.isSelected() && curve.degree > 1) {
            Tools.evalConvexHull(curve, g, true);
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void InstructionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstructionActionPerformed
        instructionDialog.setVisible(true);
    }//GEN-LAST:event_InstructionActionPerformed

    private void closeAboutDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAboutDialogActionPerformed
        aboutDialog.dispose();
    }//GEN-LAST:event_closeAboutDialogActionPerformed

    private void closeInstrDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeInstrDialogActionPerformed
        instructionDialog.dispose();
    }//GEN-LAST:event_closeInstrDialogActionPerformed

    private void convexHullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convexHullActionPerformed
        Graphics g = jPanel1.getGraphics();
        if(curve.degree > 1){
			Tools.evalConvexHull(curve, g, convexHull.isSelected());
		}
		drawPoints();
		g.setColor(curve.colour);
		curve.drawCurve(g);
    }//GEN-LAST:event_convexHullActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        clearPoints();
    }//GEN-LAST:event_clearActionPerformed

    private void deelevateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deelevateActionPerformed
        if(deelevate.isSelected()){
			Graphics g = jPanel1.getGraphics();
			curve.lowerDegree(g,1);
		}
		lowerPrompt.dispose();
    }//GEN-LAST:event_deelevateActionPerformed

    private void approxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approxActionPerformed
        if(approx.isSelected()){
			Graphics g = jPanel1.getGraphics();
			curve.lowerDegree(g,2);
		}
		lowerPrompt.dispose();
    }//GEN-LAST:event_approxActionPerformed

    private void hermiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hermiteActionPerformed
        if(hermite.isSelected()){
			Graphics g = jPanel1.getGraphics();
			curve.lowerDegree(g,3);
		}
		lowerPrompt.dispose();
    }//GEN-LAST:event_hermiteActionPerformed

    private void PWoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWoActionPerformed
        if(PWo.isSelected()){
			Graphics g = jPanel1.getGraphics();
			curve.lowerDegree(g,4);
		}
		lowerPrompt.dispose();
    }//GEN-LAST:event_PWoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JMenu Help;
    private javax.swing.JMenuItem Instruction;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem Open;
    private javax.swing.JRadioButton PWo;
    private javax.swing.JMenuItem Quit;
    private javax.swing.JMenuItem Save;
    private javax.swing.JDialog aboutDialog;
    private javax.swing.JLabel aboutText;
    private javax.swing.JRadioButton approx;
    private javax.swing.JButton clear;
    private javax.swing.JButton closeAboutDialog;
    private javax.swing.JButton closeInstrDialog;
    private javax.swing.JButton colorButton;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JButton colorChooserButton;
    private javax.swing.JDialog colorChooserDialog;
    private javax.swing.JCheckBox convexHull;
    private javax.swing.JRadioButton deelevate;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JRadioButton hermite;
    private javax.swing.JButton higherDegree;
    private javax.swing.JDialog instructionDialog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton lowerDegree;
    private javax.swing.JDialog lowerPrompt;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.ButtonGroup methods;
    // End of variables declaration//GEN-END:variables
}
